### ISSUE TITLE
Apparition can open kpat as over-sized inert full-screen window

### ISSUE THREAD

**Issue by bidmead** [Schneegans/Burn-My-Windows#356] opened 2023-07-13 10:42 UTC
Using Apparition as the window open mode, kpat can be left zoomed to larger than the physical screen and unresponsive to keystrokes or the trackpad cursor.

Steps to reproduce the behaviour:
1. Set the Burn My Windows open mode to Apparition.
2. launch kpat. The window open normally using the Apparition effect.
3. Set kpat to full screen and close it.
4. launch kpat. The Apparition effect leaves you with an over-zoomed inert window.
5. Shut down kpat and relaunch it. This time the Apparition effect leaves a normal, usable window.

Workaround 1. Open windows with a different effect, or
Workaround 2. Stick with Apparition but ensure kpat is never closed when it's full screen.

Ubuntu 23.04
Burn My Widows 35
Gnome shell 44,2
Framework Gen 11 laptop
![Apparition over-zoomed](https://github.com/Schneegans/Burn-My-Windows/assets/80772376/27668d7e-3eb5-4586-b45b-e1e366289708)

**Comment by Schneegans** [comment] 2023-07-28 11:30
Hi there! Sorry for the late reply; I am currently on vacation and checking my mail only sporadically :smiley:

This sounds somewhat similar to #335 which was fixed some releases ago. Have tried reproducing this on Wayland and X11? Does it happen on both? Also, there are some other effects which may tweak the window size. Can you reproduce this _only_ with the apparition effect? You could also try the matrix, the doom, or the t-rex effect.

**Comment by Schneegans** [comment] 2023-10-24 08:52
Is this still an issue? Else I'll close this one.

**Comment by Schneegans** [comment] 2023-10-24 17:49
Thanks for the detailed investigation! I installed KPat as well and I think that I can reproduce the issue. It seems to be unrelated to #335 even if the symptoms are similar. I added two lines of code which ensure that the window is resized to its original size at the end of the animation and this seems to fix this for me.

Is it possible for you to check out the branch `fix/#356` and test if this fixes it for you as well? This branch is for GNOME Shell versions up to 44 so it should be fine for Ubuntu 23.04, I guess.

```bash
git clone https://github.com/Schneegans/Burn-My-Windows.git
cd Burn-My-Windows
git checkout fix/#356
make install
```

Then restart GNOME Shell with <kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd> + <kbd>Enter</kbd>. Or logout / login.

**Comment by bidmead** [comment] 2023-10-24 23:09
That was educational, Simon! Linux has become so cosy this century that I
haven't compiled a single line of code since I started writing about the
operating system in the mid-90s. So this Ubuntu 23.04 I'm running here
isn't a compile environment and I had to install gettext and
libglib2.0-dev-bin for the make install to work.

But it did compile and install and the #356 fix works, tested through all
the four modes in my diagram. So thanks for some excellent swift recoding,
Simon. With extra points for deciphering my baroque bug report!

I'm going to go back to Wayland, but I can see there are still reasons
folks might want to stick with xorg a little longer. A minor point, do we
know why Kpat aways opens with Apparition *windowed* in xorg but in Wayland
the Apparition open depends on the state of the previous close (which I
assume is the designed behaviour)? Is this your fix at work, avoiding any
attempt to open full screen? If so, I'd say it was an entirely acceptable
workaround for folks clinging to xorg.

Thanks again. It's great to have restored that zany Apparition opening for
my windows. I was missing it.

--
Chris

Chris Bidmead
Freelance IT Journalist
Tested Technology <http://testedtechnology.co.uk>
@***@***.***
@chbid
🇺🇦

**Comment by Schneegans** [comment] 2023-10-25 14:53
I am glad that this is fixed on your end as well! I think that the window size is not properly restored on X11 is not related to Burn-My-Windows. I can observe this behavior even with all extensions disabled. So I guess that it is rather a limitation of KPat itself or maybe of GNOME.

Anyways, I'll soon release a new version of Burn-My-Windows including this fix. If you want to go back to the version from extensions.gnome.org, it may be the easiest to uninstall the extension and then re-install it from extensions.gnome.org!

Again thanks for the report!

**Closed by Schneegans** 2023-10-25 14:53 UTC
Labels: bug, GNOME
