### ISSUE TITLE
Glitchy visuals affecting krunner if set in the center of the screen

### ISSUE THREAD

**Issue by le-dino** [Schneegans/Burn-My-Windows#315] opened 2023-03-26 00:29 UTC
## Bug overview
If krunner is set to launch in the center of the screen, burn my windows effects pregenerate a blurred box where the effect is going to take place. Typing before the animation ends also causes extreme stretching/squashing of the box itself.
This happens with every burn my windows effect. If set on top, krunner's native animation overrides bmw and this doesn't occur. Any other window is unaffected.
Happens with both standalone effect installed from KDE store and AUR package `kwin-effects-burn-my-windows`

![BMW krunner misbehavior](https://i.imgur.com/VUp1Ttu.gif)

1. set krunner to launch in the center
2. Open krunner with any burn my windows effect

## System
 - Operating System: EndeavourOS 
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.6-arch1-1 (64-bit)
Graphics Platform: X11
Graphics Processor: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
 - Burn-My-Windows version: unsure, kde store version says 26 and seems outdated, AUR package says 27-1 updated march 5th

**Comment by Schneegans** [comment] 2023-03-26 11:53
Hi there! Thanks for the report! I think this is a duplicate of #306, right? As such it would be an issue of Kwin (see https://bugs.kde.org/show_bug.cgi?id=466227).

**Comment by le-dino** [comment] 2023-03-27 09:59
it does look the same type of misbehavior, but I'm not experiencing it anywhere other than in krunner and only when set in center mode, while that one claims to happen just on about any window. I tried using the TV glitch one and I still don't experience it anywhere else, so I'm not sure if it's the same exact issue

![tvg](https://user-images.githubusercontent.com/100118695/227909049-9539b67e-b791-46bd-9612-88a589755571.gif)

**Comment by Schneegans** [comment] 2023-03-29 17:35
I think it happens as soon as a window uses a blurred background. The blurred background is shown before the window animation is finished. This may be a regression in kwin 5.27 since users did not complain about this before :smile: 

I think also #316 is a duplicate of this.

**Comment by Schneegans** [comment] 2023-10-24 10:37
I am closing this as this seems to be [KWin issue](https://bugs.kde.org/show_bug.cgi?id=466227).

**Closed by Schneegans** 2023-10-24 10:37 UTC
Labels: bug, KDE
