### ISSUE TITLE
Transparent blurry windows have box

### ISSUE THREAD

**Issue by allancoding** [Schneegans/Burn-My-Windows#478] opened 2024-11-29 16:20 UTC
## Describe the Bug

When using any effects you get this box:
![Screenshot_20241129_090647](https://github.com/user-attachments/assets/56e6c31a-aa29-408b-8b86-5c96459bc80d)

Here is a video:

https://github.com/user-attachments/assets/47489a7d-cc71-42dc-87d5-520529ec2994

This only happens when these other effects are being used:
![Screenshot_20241129_090830](https://github.com/user-attachments/assets/db7e78a3-78e8-43d9-9e6f-58573b574935)

And the issue does not happen if the windows is opaque.

1. Go to Desktop effects in settings
2. Scroll down to appearances and enable blur
3. Set effect you want
4. Open or close a window that has the blur effect (normally any kde app with work)

Logs:
```
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_surrounding_text(const QString&, uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_surrounding_text(const QString&, uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_preferred_language(const QString&) ""
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_content_type(uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_commit_state(uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_surrounding_text(const QString&, uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_surrounding_text(const QString&, uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_preferred_language(const QString&) ""
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_content_type(uint32_t, uint32_t)
maliit.connection.wayland: virtual void Maliit::Wayland::InputMethodContext::zwp_input_method_context_v1_commit_state(uint32_t)
```

## System
_Please complete the following information:_
 - Linux distribution: Arch
 - Burn-My-Windows version: Up to date version from kde store
 - kwin: 6.2.4

**Comment by Schneegans** [comment] 2024-11-29 16:41
Thanks for the report! However, I am pretty sure that this is a duplicate of #316 and nothing which can be fixed from the effect's side. It's rather an issue how KWin draws the windows.

**Closed by Schneegans** 2024-11-29 16:41 UTC
Labels: bug, duplicate, KDE
