### ISSUE TITLE
Tried to open the settings menu

### ISSUE THREAD

**Issue by assmblyreq** [Schneegans/Burn-My-Windows#5] opened 2021-12-18 18:19 UTC
The settings of extension burn-my-windows@schneegans.github.com had an error:
```
Gtk.BuilderError: .:12:43 Invalid property: GtkViewport.scroll-to-focus
```

Stack trace:
```
PreferencesDialog@/home/darrin/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:37:19
buildPrefsWidget@/home/darrin/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:226:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Schneegans** [comment] 2021-12-18 20:44
Duplicate of #2 and #3.

**Closed by Schneegans** 2021-12-18 20:44 UTC
Labels: bug

**Comment by Schneegans** [comment] 2021-12-20 20:13
I just released Burn-My-Windows 3 which adds official support for GNOME 3.36 and 3.38.

**Comment by assmblyreq** [comment] 2021-12-20 21:56
And I just installed it. It's working flawlessly. Thank you for your work!
