### ISSUE TITLE
[KDE Plasma] Package type mismatch when updating

### ISSUE THREAD

**Issue by TheoCGaming** [Schneegans/Burn-My-Windows#325] opened 2023-04-07 22:07 UTC
## Describe the Bug
Updating Energize B through KDE Discover gives the following error:
`kwineffect.knsrc: Installation of /tmp/dhaTOL-kwin4-effect-energize-b.tar.gz failed: The new package has a different type from the old version already installed.`

1. Install Energize B version 20 or earlier from KDE Discover
2. Attempt to update it to the latest version

## System
_Please complete the following information:_
 - Distro: Arch (Zen kernel 6.2.6)
 - Version: 20 (???)
 - Plasma version: 5.27.4

**Comment by Schneegans** [comment] 2023-04-08 07:18
Hi there! Thanks for the report, yet I am pretty sure that this is a duplicate of #242.

**Closed by Schneegans** 2023-04-08 07:18 UTC
Labels: bug
