### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by psychoSherlock** [Schneegans/Burn-My-Windows#416] opened 2024-01-18 20:40 UTC
I've updated the system. This worked before and I loved your work with the window effects. But now due to the latest system update its crashed. 
![image](https://github.com/Schneegans/Burn-My-Windows/assets/81918189/edc4e4bd-2121-488b-923a-049573454703)

**Comment by Schneegans** [comment] 2024-01-19 07:24
Hi there! Thanks for the report, however this is a duplicate of the pinned issue #397. You will either have to update your Burn-My-Windows version or restart your PC.

**Closed by Schneegans** 2024-01-19 07:24 UTC
Labels: bug
