### ISSUE TITLE
Disable effects in certain applications

### ISSUE THREAD

**Issue by ayoisaiah** [Schneegans/Burn-My-Windows#263] opened 2022-12-31 23:32 UTC
I'd like to prevent the animation from working on certain applications, like my  dropdown terminal (ddterm) which I use often. Would it be possible to create a blacklist of windows where the effects are disabled? Or customise the effects per application (those this might be a little too much).

**Comment by Schneegans** [comment] 2023-01-02 12:01
Hi there! Thanks for the suggestion. However, this is a duplicate of #37, which was closed in favor of #89.

**Closed by Schneegans** 2023-01-02 12:01 UTC
Labels: feature request
