### ISSUE TITLE
Is there an eclusion list of some sort? If not, I would like to request the functionalty.

### ISSUE THREAD

**Issue by MostHated** [Schneegans/Burn-My-Windows#274] opened 2023-01-08 23:05 UTC
## The Idea
I am wondering if there is a config somewhere in which I can exclude specific windows or applications? I attempted to start the app ScreenKeys when recording a video clip to overlay the keys that I am currently typing, but BurnMyWin is activated for each key that I press and it's overlay popup.  

If this does not currently exist, I would very much like to request this feature, please.

Thanks,
-MH

**Comment by Schneegans** [comment] 2023-01-09 19:19
Hi there! Thanks for the suggestion. However, this is a duplicate of #37 and #263, which were closed in favor of #89. But it's good that you requested it anyways, as it underlines that this seems to be an important (missing) feature for many users.

I'll think about it. It will be tricky to implement this in an easy-to-understand manner. A simple exclusion list would possible; however, I would really like to combine this with per-application settings. This would include selecting "no effect" for a specific application which in turn would make the exclusion list obsolete...

**Closed by Schneegans** 2023-01-09 19:19 UTC
Labels: feature request
