### ISSUE TITLE
Choose random effect

### ISSUE THREAD

**Issue by zaka786khan** [Schneegans/Burn-My-Windows#421] opened 2024-02-14 04:45 UTC
## The Idea
I want Burn My Windows to choose a random effect every time window close/open like in Burn My Windows on GNOME. If it is possible please?

**Comment by Schneegans** [comment] 2024-02-18 18:25
Hi there! I guess you are on KDE? If so, this is a duplicate of #200 and as such not really in the scope of Burn-My-Windows. Such a functionality should be implemented as part of KWin.

**Closed by Schneegans** 2024-02-18 18:25 UTC
Labels: feature request, KDE
