### ISSUE TITLE
window has a colored box around the effect after closing or opening a app

### ISSUE THREAD

**Issue by chamychu** [Schneegans/Burn-My-Windows#347] opened 2023-06-06 10:40 UTC
## Issue
window has a white box before and after the effect starts or ends 

## Steps to reproduce the behavior
click on x on a window or start a program

## System
 - Garuda Linux
 - Burn-my-windows-32
 - 44.2

[Screencast from 2023-06-06 13-37-48.webm](https://github.com/Schneegans/Burn-My-Windows/assets/107549591/7fbabb45-5d5f-46dc-af4e-33b2ef771a22)

**Comment by Schneegans** [comment] 2023-06-06 11:42
Thanks for the report! However, this is a duplicate of #344 and will be fixed soon.

**Closed by Schneegans** 2023-06-06 11:42 UTC
Labels: bug
