### ISSUE TITLE
Problem with Alt+Tab when using effects on KDE

### ISSUE THREAD

**Issue by Z6XO** [Schneegans/Burn-My-Windows#180] opened 2022-06-30 17:34 UTC
Whenever I use alt+tab when I have the effects on, my monitors go blank and all windows and all programs close. This only happens when I have on an effect.

**Comment by Schneegans** [comment] 2022-06-30 18:26
I guess that this is a duplicate of #171. This only happens on Wayland and should be fixed in KWin 5.25.1!

**Comment by Schneegans** [comment] 2022-07-14 03:34
I think that this can be closed. Feel free to add a comment if the issue is not fixed in 5.25.1.

**Closed by Schneegans** 2022-07-14 03:34 UTC
Labels: bug
