### ISSUE TITLE
Maximize/Minimize?

### ISSUE THREAD

**Issue by ravengalqueen** [Schneegans/Burn-My-Windows#445] opened 2024-06-22 23:06 UTC
## The Idea
A clear and concise description of your idea.
If applicable, feel free to add screenshots or mock-ups to illustrate your idea!
It would be really cool if there was a setting to apply it when you are maximizing/minimizing a window instead of it only working when closing a window, maybe even have an option to use different animations on maximizing/minimizing and on closing a window
## The Alternatives
Are there alternative solutions or features you've considered?
I dont think there are any alternative solutions, if there are please let me know

**Comment by Schneegans** [comment] 2024-06-23 17:48
Hi there! Thanks for the suggestion. However, this is a duplicate of #445.

**Closed by Schneegans** 2024-06-23 17:48 UTC
Labels: feature request
