### ISSUE TITLE
Breaks window management after screen is locked.

### ISSUE THREAD

**Issue by luisbc92** [Schneegans/Burn-My-Windows#431] opened 2024-03-09 01:09 UTC
## Describe the Bug
When the extension is enabled and the desktop is locked and unlocked, the desktop becomes unstable. Some windows can be minimized but the image of the window does not actually go away. Some other windows cannot be handled at all. Eventually the whole desktop might become unresponsive.

The bug does not always occur the first time the system is locked and unlocked.

1. Enable extension and one or more of the effects.
2. Lock the screen.
3. Unlock the screen.
4. Try to move, minimize, un-minimize, close windows.

Please let me know what other information I can provide to help debug this issue. Attached is a screen recording.

Note that I do have some other extension enabled at time of recording, however this issue occurs with only Burn My Windows enabled.

## System
_Please complete the following information:_
 - Ubuntu 23.10
 - Burn-My-Windows 41
 - GNOME Shell 45.2 / Wayland
[Screencast from 2024-03-08 16-51-15.webm](https://github.com/Schneegans/Burn-My-Windows/assets/11789845/346a81b5-9ab3-4954-994a-7e9eabce6d1d)

**Comment by Schneegans** [comment] 2024-03-09 11:45
Hi there! Thanks for the report. I am on pretty much the same system. Ubuntu 23.10, GNOME Shell 45.2, and Wayland. I do not experience any of these issues. Have you really tried this with _all_ extensions disabled? Also the Ubuntu-specific build-in extensions?

I am using the vanilla GNOME desktop session, so this could be a difference.

You could run `journalctl -f -o cat` in a terminal and open a glitchy window and see if any error messages are printed. Also, you could explore the logs since the last boot with `journalctl -b -e -o cat`. Remember what the last few lines are, lock the screen, unlock the screen, and run the command once again and see if any error was printed in the mean time.

Does this produce anything meaningful?

**Comment by ahears** [comment] 2024-03-10 05:29
@Schneegans, @luisbc92:  I have the same issue. I found the extension "Dash to Dock" is the culprit. It does not re-enable correctly after unlocking/un-suspend on Ubuntu 22.04 and the button to turn it on and off works in reverse after crashing. Turning it off seems to correct the problem for me and my system returns to normal and becomes responsive again. Not the desktop crashed and I was working on the CLI to reopen the gnome-extensions-app to address this issue.

**Comment by luisbc92** [comment] 2024-03-11 22:17
I had not tried disabling built-in extensions, so I gave that a try and sure enough the issue went away.

However, now it does not occur at all! Not sure if anything updated through this whole process.

**Comment by Schneegans** [comment] 2024-03-25 19:05
According to https://github.com/micheleg/dash-to-dock/issues/2169, this could be an issue caused by Ubuntu Dock and Dash-to-Dock being enabled at the same time. I'll close this for now. Please drop a note here if this happens again!

**Closed by Schneegans** 2024-03-25 19:05 UTC
Labels: bug, GNOME
