### ISSUE TITLE
Firefox - transprent background.

### ISSUE THREAD

**Issue by chiddekel** [Schneegans/Burn-My-Windows#38] opened 2022-01-07 11:28 UTC
Small issue, when close Firefox 95.0.2 (64 bity) on Fedora 35 -  animation use transparent background instead on window as background for animation.

**Comment by Schneegans** [comment] 2022-01-07 11:42
Thanks for the report! However, this is a duplicate of #12.

**Closed by Schneegans** 2022-01-07 11:42 UTC
Labels: bug
