### ISSUE TITLE
Animations Play After Window is Visible or Before Window is Killed

### ISSUE THREAD

**Issue by erayerdin** [Schneegans/Burn-My-Windows#245] opened 2022-11-17 18:01 UTC
## Describe the Bug

1. Open a window.
2. Window is visible.
3. Animation starts to play over visible window although it should've started before it was visible.

or

1. Close a window.
2. Animation starts to play on visible window although the window should've gone invisible with the animation.

![2022-11-17_20-55](https://user-images.githubusercontent.com/2399084/202521716-b4697125-a546-4bf5-a7c2-c849fcc6b1a2.png)

I managed to catch a screenshot as it happens when I close my window.

As you can see, this fire effect rolls over the closing window, but the content of the window is still visible while it's doing that.

This happens with *any* animation, whether it's hexagon, pixel wipe, etc.

## System
_Please complete the following information:_
 - Linux distribution: Fedora KDE 36
 - Burn-My-Windows version [e.g. Burn-My-Windows 5, or commit SHA] I don't know how to get, but latest version at the date of this issue

```plain
Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.8-200.fc36.x86_64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-2400 CPU @ 3.10GHz
Memory: 15,6 GiB of RAM
Graphics Processor: AMD OLAND
```

**Comment by Schneegans** [comment] 2022-11-17 22:02
Thanks for the report! Is this maybe a duplicate of #223?

**Comment by erayerdin** [comment] 2022-11-18 08:38
Yep, it's a duplicate of that. Feel free to close this issue and reopen #223 again if you'd like to.

**Comment by Schneegans** [comment] 2022-11-18 10:33
Why should I reopen this? The issues has been fixed, it was a regression in KWin. I think you only have to update to at least KWin 5.26.1.

**Comment by Schneegans** [comment] 2022-11-25 14:40
I guess this can be closed now? Or do you think that this is a different issue?

**Comment by erayerdin** [comment] 2022-11-25 21:22
Yeah, can be closed. Kwin update will arrive to Fedora anytime soon anyway. Since you are the owner, I expect you to close it if you'd like to.

**Closed** 2022-11-25 21:23 UTC
Labels: bug, KDE
