### ISSUE TITLE
Enable / disable animation from respective options page

### ISSUE THREAD

**Issue by dasnoopy** [Schneegans/Burn-My-Windows#66] opened 2022-01-22 12:20 UTC
## The Motivation
Maybe relative to #60 : to understand better which aanimations are enabled  you can consider to add an option 
enable/disable in the respective  settings page and remove the current selection from list in the general options page

## The Solution
one image is better than 1000 words  (just a mockup...)

![Screenshot from 2022-01-22 12-35-15](https://user-images.githubusercontent.com/296922/150638114-c99a27ab-37ab-424d-a9b1-d00e6e54e44b.png)

in addition, the label of active animations  could be in bold 

## The Alternatives
put the label of active animations  in bold and leave how to choose animations as is..

Thanks
Andrea

**Comment by dasnoopy** [comment] 2022-01-22 12:22
oops..  in the mockup the option should be "Enable animations"  not "Enable effect"
Regards

**Comment by Schneegans** [comment] 2022-01-22 19:06
Thanks for the suggestion - that's a nice mockup :smile: 

I like the idea, yet I am a bit hesitant. The problem is, that there will be the possibility to use effects for the window-open animation in the future as well. While it could be possible to add two switches to each effect's page, it would be rather difficult to show in the sidebar which effect is enabled for opening and / or closing.

Having a good overview on which effects are enabled is important IMHO. So we would need to keep the drop-down(s) on the general page. And in this case, the switches would be quite redundant...

There will be an effect-preview button (#61, most likely in the next version). Maybe that would be sufficient?

**Comment by Schneegans** [comment] 2022-03-23 05:07
I'll close this as we have the preview buttons now.

**Closed by Schneegans** 2022-03-23 05:07 UTC
