### ISSUE TITLE
Can't activate effect with KDE

### ISSUE THREAD

**Issue by trolldu47** [Schneegans/Burn-My-Windows#377] opened 2023-08-23 09:03 UTC
Hello,
I just followed the tutorial found in the README to install Burn my windows with kde except that when I finished the installation I just select my effect in Desktop Effect nothing happens but I close window.  J4ai tries to change effect and restart and it still changes nothing is what you can help me.  Thanks in advance. Sorry if what I wrote and weird I'm with a translator.

**Comment by Schneegans** [comment] 2023-08-23 09:04
This could be a duplicate of #376. Could you try what I suggested there?

**Comment by trolldu47** [comment] 2023-08-23 09:09
I just looked at the post except that I don't have the same error as him in the journalctl -f -o cat |  grep -E 'burn-my-windows|'  I have this error that keeps repeating itself AVC apparmor="DENIED" operation="ptrace" class="ptrace" profile="snap.discord.discord" pid=2434 comm="Utils" requested_mask="read" denied_mask="read" peer="unconfined"

**Comment by Schneegans** [comment] 2023-08-23 09:12
I think that message is unrelated. Are you sure that you are at least on KWin 5.25.0?

**Comment by trolldu47** [comment] 2023-08-23 09:17
When I do kwin --version I get this:
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
kwin 5.24.7

**Comment by Schneegans** [comment] 2023-08-23 09:33
Well, then that's the issue. You'll need at least KWin 5.25 for the effects to work :cry:

**Closed by Schneegans** 2023-08-23 09:33 UTC
Labels: bug, KDE

**Comment by trolldu47** [comment] 2023-08-23 21:39
ah yes sorry I had not seen sorry for the disturbance
