### ISSUE TITLE
Not working with Fedora 39

### ISSUE THREAD

**Issue by NavTech270** [Schneegans/Burn-My-Windows#398] opened 2023-11-08 10:07 UTC
## Bug

The settings of extension burn-my-windows@schneegans.github.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/naveenvatti/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/prefs.js:29:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command.
Execute this in a terminal and observe the output while reproducing the bug.

```bash
journalctl -f -o cat | grep -E 'burn-my-windows|'
```

## System
 - Fedora 39 
 - Burn-My-Windows Version 40
 - GNOME Shell version: 45.1

**Comment by Schneegans** [comment] 2023-11-08 10:21
Thanks for the report! But this is most likely a duplicate of #397, #394, and #395 :wink:

**Closed by Schneegans** 2023-11-08 10:21 UTC
Labels: bug
