### ISSUE TITLE
GNOME 45: import declarations may only appear at top level of module

### ISSUE THREAD

**Issue by x9sim9** [Schneegans/Burn-My-Windows#397] opened 2023-11-08 07:41 UTC
## Describe the Bug
Seems like Gnome 45 decided to "simplify" imports and in the process break a huge number of extensions, hopefully its not too big a job to fix this but depending on how you manage imports this might take a while to implement

Install Gnome 45 

## System
Ubuntu 23.10
BMW v40
Gnome 45.0

**Comment by Schneegans** [comment] 2023-11-08 08:49
Thanks for the report. But this is a duplicate of #394 and #395. Burn-My-Windows supports GNOME 45 [since version 38](https://github.com/Schneegans/Burn-My-Windows/releases/tag/v38) which has been released two months ago :wink:

**Closed** 2023-11-08 08:49 UTC
Labels: bug
