### ISSUE TITLE
Applications like Godot break when using Pop Shell tiling extension and Burn-My-Windows

### ISSUE THREAD

**Issue by BenHerbst** [Schneegans/Burn-My-Windows#166] opened 2022-06-07 22:42 UTC
## Describe the Bug
I open Godot for example and select my project while I activated the Pop shell tiling. Then Godot just gets black and copies each frame lot of times. So it is just strange. I have animation set for opening windows. I also have set for closing but I do not think that causes the issue.

1. Get for example Godot
2. Get pop shell
3. Activate tiling
4. Open Godot
5. Open project in Godot

I think it just doesn't refresh the window correctly. After minimizing and reopening, the issue is solved until next Godot start.

## System
_Please complete the following information:_
 - Linux distribution: Pop!_OS 22.04
 - Burn-My-Windows version: 16
 - GNOME Shell version: 42.1

**Comment by Schneegans** [comment] 2022-06-16 03:48
Hi there! Thanks for the report (and sorry for the late reply).

I haven't yet found the time to reproduce this (this will require setting up a VM). In the mean time, could you please run `journalctl -f -o cat` in a terminal and then open Godot while the command is still running? It would be very nice if you could do a short screen recording of what happens so that I get a better I dea how this bug looks like...

Thank you!

**Comment by BenHerbst** [comment] 2022-06-16 16:50
https://www.dropbox.com/s/nr8a0811qalsj3x/Bildschirmaufzeichnung%20vom%2016.06.2022%2C%2018%2021%2025.mp4?dl=0
This is the video.

You could also just provide a checkbox or so where the user can select to not show start animations for windows, so only popups have them.

As this issue only happen when in tiling mode and in tiling mode, animations on window startup not work, only for popups.

Keep up the great work! 👍👍

**Comment by gabrc52** [comment] 2023-01-21 08:38
Which graphics card are you using and which drivers (i.e. proprietary or open source)?

**Comment by Schneegans** [comment] 2023-01-21 11:10
Btw, once #89 is implemented, this will serve as a workaround for this problem :wink:

**Comment by Schneegans** [comment] 2023-02-15 12:39
#292 got merged to `main`! I think this can be used to configure a work-around for this problem. If you still encounter any issues after BMW 27 got released, please drop a note here!

**Closed by Schneegans** 2023-02-15 12:39 UTC
Labels: bug, GNOME
