### ISSUE TITLE
strange glitch in maximize apps, see attachment 

### ISSUE THREAD

**Issue by sdimitrov7** [Schneegans/Burn-My-Windows#340] opened 2023-05-21 05:27 UTC
When I have the extension enabled, I encounter a problem with applications like Thunderbird, KeePassXC, Terminal, and Slack. The issue occurs when I maximize the application window. If I close it and reopen it, the problem persists.
## System
 - Linux distribution Ubuntu 23.04
 - Burn-My-Windows version 31
 - GNOME Shell version: 44

https://github.com/Schneegans/Burn-My-Windows/assets/129307860/235c7b35-31af-4fec-b7b4-922ce6db0212

**Comment by Schneegans** [comment] 2023-05-22 04:14
Hi there! Thanks for the report, but I think that this is a duplicate of #335.

**Closed by Schneegans** 2023-05-22 04:14 UTC
Labels: bug
