### ISSUE TITLE
Idea: settings to enable an effect at open/close/both

### ISSUE THREAD

**Issue by CeeHgh** [Schneegans/Burn-My-Windows#442] opened 2024-06-09 06:30 UTC
Loving this extension.

Just an idea: to me, some effects look more suited for a window open, rather than close, and some seem better to happen at close rather than open.
Could there be a setting to enable an effect to be employed just for open, close, or both open & close (with that being the default, perhaps)?
I feel this would work great when multiple effects are enabled.

**Comment by Schneegans** [comment] 2024-06-09 06:39
Hi there! If you are on KDE, this is a duplicate of #173. On GNOME, this is already possible: Just checkout the profile options at the top of the settings dialog!

**Closed** 2024-06-09 06:48 UTC
Labels: feature request

**Comment by CeeHgh** [comment] 2024-06-09 18:59
I saw the profile options, but that only seems to allow you to specify the animation type to use for all your selected effects, unless I've missed something.
I was thinking more along the lines of being able to specify separate lists of effects for each of open and close, and have them both active.
For example, for window close: Broken Glass & Incinerate, and for window open: TV Effect. So, I'd see TV Effect with every window open and one chosen randomly from Broken Glass and Incinerate with every window close.

**Comment by CeeHgh** [comment] 2024-06-09 19:26
Ahhhh, I see how to do it now. The profiles act together, rather than alone.

For anyone else reading this and making the same assumption I did: I set my open effects in the standard profile, then created a new profile for closing windows, and made it higher priority. The toggle in the main configuration window allows me to switch and set which effects go in which profile.
