### ISSUE TITLE
Can I make the effect only on exit the window ?

### ISSUE THREAD

**Issue by gammer1608** [Schneegans/Burn-My-Windows#410] opened 2024-01-01 07:17 UTC
Can I make the effect only on exit the window  , I am using kubuntu.

**Comment by Schneegans** [comment] 2024-01-01 18:19
Hi there! Thanks for the suggestion, but this is a duplicate of #173. This is not yet possible and also not really planned as I think that this should be implemented into KWin. However, if anyone volunteers to implement this on the Burn-My-Windows side of things, I would happily accept a pull request!

**Closed by Schneegans** 2024-01-01 18:19 UTC
Labels: feature request, KDE
