### ISSUE TITLE
"Shaking" windows. 

### ISSUE THREAD

**Issue by tengl** [Schneegans/Burn-My-Windows#244] opened 2022-11-15 14:39 UTC
## Describe the Bug
Some applications starts "shaking" after they have started, especially Google Chrome. Firefox does not. 

They cannot be interacted with. Closing the windows with SUPER + Q works and shows the effect. 

```bash
journalctl -f -o cat | grep -E 'burn-my-windows|'

Started Application launched by gnome-shell.
asked to register item /org/freedesktop/secrets/collection/login/2, but it's already registered
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55a19e26a360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55a1a9413b00] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55a1a0e9c6e0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspaceAnimation_MonitorGroup>:0x55a1adeb59b0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55a1a3945f70] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_ui_workspaceAnimation_WorkspaceGroup>:0x55a1a9a1b8f0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterClone>:0x55a1a9a48b80] is on because it needs an allocation.
app-gnome-google\x2dchrome-289068.scope: Consumed 10.548s CPU time.
```

## System
 - Linux distribution: Pop!_OS 22.04
 - Burn-My-Windows version 22
 - GNOME Shell version: 42.4

**Comment by tengl** [comment] 2022-11-15 14:46
It is probably a conflict with the auto move windows extension. https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions/auto-move-windows. I've got that enabled for Chrome, but also for Firefox. 

It seems to work if I disable it.

**Comment by Schneegans** [comment] 2022-11-17 11:05
Thanks for the report! However, I cannot reproduce this (yet). Have you tried disabling all other extensions (except for Auto Move Windows and Burn-My-Windows)? Have you tried this both on X11 and Wayland?

**Comment by tengl** [comment] 2022-11-22 07:50
I've only used X11. I haven't tried Wayland yet, I might do that when I get the time. 

I have two Google accounts in Chrome, so I get a dialog where I need to select which user I should use. That might have something to do with it, but I don't think so. I've seen it on other windows too.

**Comment by Schneegans** [comment] 2023-04-05 07:46
I just had to do some severe refactoring of Burn-My-Windows to fix some issues on GNOME 44. As a side effect, this could have fixed this issues as well. If you want to, you can [test the latest development version](https://github.com/Schneegans/Burn-My-Windows#c-cloning-the-latest-version-with-git) and see if the issue is fixed!

**Comment by Schneegans** [comment] 2023-05-04 14:36
I'll close this for now, please add a comment if that's still an issue!

**Closed by Schneegans** 2023-05-04 14:36 UTC
Labels: bug, GNOME

**Comment by tengl** [comment] 2024-03-27 07:39
Sorry for the somewhat late reply, I haven't used the extension the past year, but I tried it again now and it seems to work so far. Great job.
