### ISSUE TITLE
Plasma 6 Glitches

### ISSUE THREAD

**Issue by mmcnutt** [Schneegans/Burn-My-Windows#406] opened 2023-12-02 03:51 UTC
## Describe the Bug
Thank you for updating for plasma 6 compatibility. Running the current git main there are 2 minor issues under plasma 6 (5.27.80). With the transparency "Blur" effect enabled, the window is rendered as a blurred box and the animation is played over it, disabling the blur effect hides this issue. 

The other issue I've found is that the settings buttons to tweak the effect parameters are not available on the settings page, the buttons are simply not rendered.

1. Follow instructions to build and install main
2. Close any window with the blur effect enabled
3. Blank "pane" of blur is rendered and the effect plays over it. 
4. Turning off blur, effect plays correctly

[Here is a video example ](https://mattmcnutt.net/s/599C7S6mTZe895f)

 System
 - Linux distribution Fedora Kinoite Rawhide.20231201.n.0 (2023-12-01T06:11:34Z)
 - Burn-My-Windows version Git - 219d4f9458996b6977d328bcc6a2370c8dbffe76
 - GNOME Shell version: Plasma 6 alpha - 5.27.80

**Comment by Schneegans** [comment] 2023-12-03 04:44
Hi there! Thanks for the report.

The first issue you are describing is a duplicate of #316.

The second issue seems new. Do you mean that there is no button to access the effect-settings in the system-preferences dialog or are there simply no widgets inside the actual effect-settings dialog? I currently do not have Plasma 6 running, so I cannot test this myself :disappointed:

**Comment by Schneegans** [comment] 2024-01-01 18:56
Sorry for the late reply. I just looked into this and it's quite hard to figure out as I currently have no Plasma 6 up and running. I suspect that [this commit](https://invent.kde.org/plasma/kwin/-/commit/7ae4497d5baa516e9c9fc67aa23e333b5e25aae5) is related.

Could you try replacing the `"X-KDE-PluginKeyword": "%DIR_NAME%",` in [`metadata.json.in`](https://github.com/Schneegans/Burn-My-Windows/blob/main/kwin/metadata.json.in#L24) with `"X-KDE-ConfigModule": "kcm_kwin4_genericscripted",` and see if this helps?

**Comment by mmcnutt** [comment] 2024-01-02 00:05
I just made that change and recompiled it

This has fixed the issue, the buttons are now back and the effects can be tweaked

**Comment by Schneegans** [comment] 2024-01-02 06:05
Awesome! Then I'll check if this is still compatible with Plasma 5 ASAP.

**Closed** 2024-01-02 19:43 UTC
Labels: bug, KDE
